---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	collapse = TRUE,
	comment = "#>")
library(monpackage)
```

```{r}
knitr::opts_chunk$set(
	message = TRUE,
	warning = TRUE,
	collapse = TRUE,
	comment = "#>"
)
install_load_packages("installr")
```

```{r}
knitr::opts_chunk$set(
	message = TRUE,
	warning = TRUE,
	collapse = TRUE,
	comment = "#>"
)
pool_imputations(c(45,42),c(14,19),2)
```

```{r}
knitr::opts_chunk$set(
	message = TRUE,
	warning = TRUE,
	collapse = TRUE,
	comment = "#>"
)

simulation_NA(c(NA,45,48,65,47),40,5)
```

```{r}
knitr::opts_chunk$set(
	message = TRUE,
	warning = TRUE,
	collapse = TRUE,
	comment = "#>"
)

simulation_LD(c(0,45,48,65,47),40,5)
```

```{r}
knitr::opts_chunk$set(
	message = TRUE,
	warning = TRUE,
	collapse = TRUE,
	comment = "#>"
)

nice_colors()$bysex
```

```{r}
knitr::opts_chunk$set(
	message = TRUE,
	warning = TRUE,
	collapse = TRUE,
	comment = "#>"
)

Pierre <- c(8,9,15)
Nathalie <- c(17,12,13)
Jacques <- c(11,15,7)
Julie <- c(5,12,19)
matrice <- matrix(c(Pierre, Nathalie, Jacques, Julie), nrow=4, ncol=3, byrow=T)
cortest(matrice)
```

```{r fig.height=8, fig.width=8}
knitr::opts_chunk$set(
	message = TRUE,
	warning = TRUE,
	collapse = TRUE,
	comment = "#>"
)

Dist.forme(c(14,15,18,21,20,22))
```

```{r}
knitr::opts_chunk$set(
	message = TRUE,
	warning = TRUE,
	collapse = TRUE,
	comment = "#>"
)

data<-as.data.frame(c("all","girls","all","all","boys"))
colnames(data)<-"pop"

boxsize_forestplot(data)
```

```{r}
knitr::opts_chunk$set(
	message = TRUE,
	warning = TRUE,
	collapse = TRUE,
	comment = "#>"
)

data<-as.data.frame(c("all","girls","all","girls","boys","boys"))
colnames(data)<-"pop"
data$Pvalue<-c(0.05,0.02,0.1,0.001,0.8,0.05)
data$Estimate<-c(1.1,1.2,2.3,1.26,1.01,1.1)
data$CI<-c("[1.05,1.15]","[1.15;1.25]","[0.9;3.1]","[1.20;1.30]","[0.6;1.6]","[1.05,1.15]")

text_forestplot(data,c("example n째1","example n째2"))
```

```{r fig.height=8, fig.width=8}
knitr::opts_chunk$set(
	message = TRUE,
	warning = TRUE,
	collapse = TRUE,
	comment = "#>"
)

data<-as.data.frame(c("all","girls","all","girls","boys","boys"))
colnames(data)<-"pop"
data$Pvalue<-c(0.05,0.02,0.1,0.001,0.8,0.05)
data$Estimate<-c(1.1,1.2,2.3,1.26,1.01,1.1)
data$LowerCL<-c(1.05,1.15,0.9,1.20,0.6,1.05)
data$UpperCL<-c(1.15,1.25,3.1,1.30,1.6,1.15)
data$CI<-c("[1.05,1.15]","[1.15;1.25]","[0.9;3.1]","[1.20;1.30]","[0.6;1.6]","[1.05,1.15]")

forestplot_sex(data,c("example n째1","example n째2"),"Example")

```

```{r}
knitr::opts_chunk$set(
	message = TRUE,
	warning = TRUE,
	collapse = TRUE,
	comment = "#>"
)

tercile(c(112,15,18,15,415,41,5,4,44,51,51,2,65,4,8,5,5,8,45,489))
```

```{r}
knitr::opts_chunk$set(
	message = TRUE,
	warning = TRUE,
	collapse = TRUE,
	comment = "#>"
)

getmode (c(112,15,18,15,415,41,5,4,44,51,51,2,65,4,8,5,5,8,45,489))

```

```{r}
knitr::opts_chunk$set(
	message = TRUE,
	warning = TRUE,
	collapse = TRUE,
	comment = "#>"
)

data<-as.data.frame(c(1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1))
colnames(data)<-"hyperactivity"
data$sex<-c(1,1,2,1,1,2,1,1,1,1,1,2,2,2,1,1,1,1,2,1)
data$id<-seq(1,length(data$hyperactivity))
appariement_cond(data,data$hyperactivity,data$sex,1,2,"id")

```

```{r}
knitr::opts_chunk$set(
	message = TRUE,
	warning = TRUE,
	collapse = TRUE,
	comment = "#>"
)
x<-c(15,7,5,1,8,0,85,0)
transform_log_plus_c(x)

```
